# Generated by Django 5.1.4 on 2024-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
