# Generated by Django 5.1.4 on 2024-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticket/file'),
        ),
    ]
