# Generated by Django 5.1.4 on 2025-01-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
