# Generated by Django 3.1.12 on 2025-01-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_subject'),
        ('ticket', '0009_message_user'),
    ]

    operations = [
    ]
